'use strict';
const assert = require('node:assert/strict');
const {sumarFracciones,resumirDatos}=require('./interacciones');
assert.deepEqual(sumarFracciones(-1,2,3,4),{n:1,d:4,valor:.25});
assert.deepEqual(sumarFracciones(-3,4,1,2),{n:-1,d:4,valor:-.25});
assert.deepEqual(sumarFracciones(1,2,-1,2),{n:0,d:1,valor:0});
assert.throws(()=>sumarFracciones(1,0,1,2));
assert.deepEqual(resumirDatos([10,12,12,14,42]),{media:18,mediana:12,rango:32});
assert.deepEqual(resumirDatos([4,1,2,3]),{media:2.5,mediana:2.5,rango:3});
assert.throws(()=>resumirDatos([]));
assert.throws(()=>resumirDatos([-1,2]));
console.log('8 comprobaciones matemáticas aprobadas.');

const {leerRespuesta}=require('./racionales');
assert.equal(leerRespuesta('2/8'),.25);
assert.equal(leerRespuesta('0,25'),.25);
assert.equal(leerRespuesta('-1/4'),-.25);
assert.equal(leerRespuesta('1/0'),null);
assert.equal(leerRespuesta(''),null);
assert.equal(leerRespuesta('abc'),null);
assert.equal(leerRespuesta('Infinity'),null);
console.log('7 comprobaciones del ingreso de respuestas aprobadas.');
const {urlFormulario}=require('./participar');
assert.equal(urlFormulario('https://forms.gle/ejemplo'),'https://forms.gle/ejemplo');
assert.equal(urlFormulario('https://docs.google.com/forms/d/e/ejemplo/viewform'),'https://docs.google.com/forms/d/e/ejemplo/viewform');
assert.equal(urlFormulario('https://forms.office.com/r/abc123'),'https://forms.office.com/r/abc123');
assert.equal(urlFormulario('https://forms.office.com/Pages/ResponsePage.aspx?id=abc'),'https://forms.office.com/Pages/ResponsePage.aspx?id=abc');
for(const v of ['', 'javascript:alert(1)', 'https://docs.google.com/forms/d/abc/edit', 'https://forms.gle.ejemplo.com/a', 'http://forms.gle/a', 'https://usuario@forms.gle/a'])assert.equal(urlFormulario(v),null);
console.log('10 comprobaciones de enlaces de formularios aprobadas.');
const {construirTriangulo}=require('./geogebra');
const commands=[];
assert.equal(construirTriangulo({evalCommand(command){commands.push(command);return !command.includes('Round(');}}),true);
assert(commands.some(command=>command.includes('round(area,2)')));
assert.equal(construirTriangulo({evalCommand(command){return !command.startsWith('Text(');}}),false);
assert.equal(construirTriangulo({evalCommand(command){if(command.startsWith('Text('))throw Error('Texto no disponible');return true;}}),false);
console.log('4 comprobaciones de construcción y etiqueta opcional GeoGebra aprobadas.');
